### ISSUE TITLE
IntranetUserJS: Remove excess spaces

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-remove-excess-spaces#1]
IntranetUserJS: Remove excess spaces

/* Poista asiakkaan muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/ (input)
/* Poista asiakkaan muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/ (textarea)
/* Poista niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/
/* Poista kausijulkaisun vastaanottonäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/
/* Poista hankinnassa uuden tilauksen niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä */
  /* Poista hankinnassa uuden tilauksen niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä */  /* Tämä ei toimi */ TESTATTAVA/KORJATTAVA

**Comment by lmstrand** [comment]
Testaus:

Poista kyseiset rimpsut käytöstä intranetUserJS-asetuksesta.

Aktivoi plugin.

Testaa, että ylimääräiset välilyönnit poistuvat rimpsujen kuvausten mukaisissa paikoissa.

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa otettu käyttöön plugin ja poistettu vastaavat rimpsut intranetUserJS-asetuksesta.:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by lmstrand** [comment]
Vaskilla on tosiaan oma versio pluginin viimeisen rimpsun kommentin mukaan toimimattomasta rimpsusta:

// Poista hankinnassa uuden tilauksen niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä /cgi-bin/koha/acqui/neworderempty.pl? //*** 30.4. Lisätty delay. Auttaa napaamaan kiinni niihin kenttiin, joihin aiemmin ei tarttunut. Hinta- ja prosenttikentissä välistä pitäisi saada kaikki välilyönnit pois.
//Testattu, muuten kaikki toimii, hinta- ja prosenttikentissä ei poista välilyöntejä keskeltä esim 3.33e mutta ilmoittaa kyllä olevan virheellisessä muodossa.

**Comment by pknuuti** [comment]
Mä en löydä Vaaran nextiltä tätä plugaria.

**Comment by lmstrand** [comment]
Nyt on lisätty.

**Comment by Rvallim0** [comment]
Vaskissa nextillä plugari testattu, kausijulkaisutilauksen "Lisänumero"-kentästä välilyöntien poisto ei toimi, testillä toimi. Tästä kentästä siirtyy tieto myös suoraan "Sarjanumero"-kenttään. Muilta osin plugari vaikutti toimivan hyvin. 
![kuva](https://github.com/user-attachments/assets/0d00e4ea-a26b-49b3-98a9-8a5ad0a3c7f9)

**Comment by Tuomas-Kyyti** [comment]
Kyytin Nextillä tuo lisänumero / sarjanumero toimivat niin, että kun lisänumeroon löi noita välilyöntejä ja tuli pois kentästä, niin välilyönnit poistuivat lisänumero-kentästä. Tiedot siirtyivät samalla sarjanumero-kenttään, johon ylimääräiset välilyönnit jäivät. Jos sitten meni tuohon sarjanumero-kenttään ja tuli siitä pois, niin silloin ylimääräiset välilyönnit poistuivat siitäkin.

**Comment by MikkoLiimatainen** [comment]
Vaskissa on rimpsu, joka pitää nuo lisänumeron ja sen sarjanumeron synkassa, eli jos toista kenttää muuttaa, niin toinenkin muuttuu automaattisesti. Rimpsujen suoritusjärjestys on muuttunut plugarisoinnin takia ja se vaikuttaa näiden rimpsujen yhteispeliin. Laitoin tekemääni rimpsuun oman välilyöntien poistonsa ja nyt se toimii. Täytynee kuitenkin miettiä tuon tarpeellisuutta.

**Comment by MikkoLiimatainen** [comment]
> Vaskilla on tosiaan oma versio pluginin viimeisen rimpsun kommentin mukaan toimimattomasta rimpsusta:
> 
> // Poista hankinnassa uuden tilauksen niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä /cgi-bin/koha/acqui/neworderempty.pl? //*** 30.4. Lisätty delay. Auttaa napaamaan kiinni niihin kenttiin, joihin aiemmin ei tarttunut. Hinta- ja prosenttikentissä välistä pitäisi saada kaikki välilyönnit pois. //Testattu, muuten kaikki toimii, hinta- ja prosenttikentissä ei poista välilyöntejä keskeltä esim 3.33e mutta ilmoittaa kyllä olevan virheellisessä muodossa.

Luulen, että plugarisointi on korjannut nuo hankinnan niteen muokkausnäytön skriptit, koska rimpsujen suoritusjärjestys on muuttunut. Tai sitten tuota sivua on muuten parannettu, kun nämä rimpsut näyttävät toimivan. Aiemmin olin tosiaan paikannut ongelmaa laittamalla viiveen koodiin, jotta tuo erikseen ladattava niteen muokkaus ehtii muodostua sivulle ja rimpsut saa tarttumaan kenttiin, mutta nyt tuo toimii ilman viivettä.

**Comment by lmstrand** [comment]
Sain korjattua tuon lisänumero-kentän siivouksen vähän eri tavalla kuin muissa kentissä. Testattavana nexteillä.

**Comment by Rvallim0** [comment]
Vaski nextillä nyt kokeiltu, vaikuttaa toimivan hyvin tuo kenttä nyt.

**Comment by LeenaKinnunen** [comment]
Lapissa plugari käytössä ja näyttäisi toimivan.

**Comment by ElinaUotila** [comment]
Kirkesissä plugari aktivoitu ja toimi testatessa.

**Comment by LastuJanneS** [comment]
Lastu myös kuittaa toimivaksi

**Comment by AnneliO** [comment]
Kaikki kimpat ovat nyt kuitanneet, joten suljen tiketin. :)
